apiVersion: apps/v1
kind:
  Deployment
metadata:
  name: account-service
  namespace: default
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: registry.gitlab.com/reneralmeida/pi-ii/accounts-service
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: CLIENT_ID_BACKEND
              value:
            - name: CLIENT_SECRET_BACKEND
              value:
            - name: JWT_ISSUER_URI
              value:
            - name: KEYCLOAK_SERVER_URL
              value:
            - name: REALM_TOKEN_URI
              value:
            - name: ACC_SVC_DB_URL
              value:
            - name: ACC_SVC_DB_USER
              value:
            - name: ACC_SVC_DB_PASS
              value:
            - name: S3_ACCESS_KEY_ID
              value:
            - name: S3_SECRET_ACCESS_KEY
              value:
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: gitlabcred